### ISSUE TITLE
Vol Directory path disappears after selecting it

### ISSUE THREAD

**Issue by HxVideoGameRev** [Syroot/io_scene_mk8muunt#1]
I'm Having a hard time putting in the Directory, 

Whenever i select the Directory path it just disappears in blender

An example of this would be  

C:\Users\MyComputerName\Desktop\Wii U mods\Wii U Tools\Mario Kart 8 Game files\Files\

**Comment by RayKoopa** [comment]
This happens only if the game dump is flawed. Are you sure you have a full and correct game dump? Most importantly, objflow.byaml has to exist.

**Comment by RayKoopa** [comment]
I made a small update to the selection method. Please delete the old version and install the new 0.5.6 one, then have a look at the updated wiki installation instructions.

**Comment by RayKoopa** [comment]
Guess it's fixed now.

**Comment by HxVideoGameRev** [comment]
Thanks!
