### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by pytoxfx** [Syroot/io_scene_mk8muunt#2]
I cant install the addon(py files) it doesnt matter if i install theme file by file or all together i always get an error message.

**Comment by RayKoopa** [comment]
An exact installation guide is found [here](https://github.com/Syroot/io_scene_mk8muunt/wiki/Installation).
About the error message, please screenshot it or copy it from the Blender console, as it is required for further assistance.

**Comment by RayKoopa** [comment]
That doesn't like an error, just an information message, though I don't know why it appears at all. I guess you tried another way of installing it, sadly I only support the (slightly manual) one on the wiki at this time. The add-on will be rewritten some time in the future anyway.

**Comment by pytoxfx** [comment]
ok so now it worked but how do i install the bfres addon?
and thanks for the installing guide i dont know why i didnt find it.
btw i tried installing this addont the ussual way :/

**Comment by pytoxfx** [comment]
ok so i got it working but the maps dont really get imported

**Comment by RayKoopa** [comment]
You also need to set up and configure *io_scene_bfres* to import model data. It also has [installation and usage instructions](https://github.com/Syroot/io_scene_bfres/wiki/Installation).
